name: Build and test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      DUCKDB_GIT_VERSION: "v1.2.0"
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        # In order to fetch changed files
        with:
          fetch-depth: 0
      - name: Checkout DuckDB source code
        run: |
          git submodule init && git submodule update
          make set_duckdb_version
      - name: Build extension
        run: make
      - name: Run tests
        run: make test
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: csv_scanner.duckdb_extension
          path: build/release/extension/csv_scanner/csv_scanner.duckdb_extension
