name: Build wasm binary

on:
  push:
    branches:
      - master

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: |
          cd dockerfiles/build-wasm
          docker build --tag duckdb-build-wasm ../.. -f ./Dockerfile
      - name: Copy wasm binary from the built image
        run: |
          cd dockerfiles/build-wasm
          docker create --name temp duckdb-build-wasm
          docker cp temp:/workspace/csv_scanner.duckdb_extension.wasm .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: csv_scanner.duckdb_extension.wasm
          path: dockerfiles/build-wasm/csv_scanner.duckdb_extension.wasm
